in:
  type: dynamodb
  region: ap-northeast-1
  table: users
  endpoint: "http://localhost:8000"
  schema:
    id:
      type: string
    name:
      type: string
    age:
      type: number
    created_at:
      type: number
out:
  type: file
  filepath: ./output.jsonl
  format: jsonl
#out:
#  type: bigquery
#  location: asia-northeast1
#  projectId: default-364617
#  datasetId: test
#  tableId: users_test
#  # endpoint: "http://localhost:9050"
#  schema:
#    id:
#      type: string
#    name:
#      type: string
#    age:
#      type: integer
#    created_at:
#      type: integer
