in:
  type: sql
  driver: mysql
  table: users
  database_url: root:root@tcp(localhost:3306)/test
  schema:
    id:
      type: string
    name:
      type: string
    age:
      type: int
    created_at:
      type: int
out:
  type: file
  filepath: ./output.jsonl
  format: jsonl
